package com.git.recruitment.event;

public enum UserActionType {
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    CV_SHORTLISTED,
    CV_REJECTED,
    PROFILE_UNDER_REVIEW,
    PROFILE_UPDATED,
    PROFILE_DELETED,
    APTITUDE_SCHEDULED,
    APTITUDE_RESULT_RECORDED,
    INTERVIEW_SCHEDULED,
    ROUND_SCHEDULED,
    ROUND_RESULT_RECORDED,
    APPLICATION_REJECTED,
    FINAL_DECISION_RECORDED
}
